name: Node.js CI

on:
  push:
    branches: [ "develop","main" ]
  pull_request:
    branches: [ "develop","main" ]

jobs:
  CI:
    runs-on: node:14-slim
    steps:
    - name: Install
      run: npm ci  
    - name: Test
      run: npm run test
    - name: Dependency Check
      run: npm audit